#source ~/.fonts/*.sh

export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/code
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv



source $ZSH/oh-my-zsh.sh
source "$HOME/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
source "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source ~/.local/bin/virtualenvwrapper.sh

ZSH_THEME="spaceship"
SPACESHIP_TIME_PREFIX="╰─("
SPACESHIP_TIME_SUFFIX=")"
SPACESHIP_TIME_SHOW=true

SPACESHIP_VENV_PREFIX=""
SPACESHIP_VENV_SUFFIX=" "
SPACESHIP_VENV_SYMBOL=" "
SPACESHIP_VENV_COLOR=blue

SPACESHIP_NODE_PREFIX=" "
SPACESHIP_NODE_SUFFIX=""

SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_CHAR_SYMBOL="➤  "
# SPACESHIP_CHAR_COLOR_SUCCESS=white
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_GIT_PREFIX=" "
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_JOBS_COLOR=red
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_DIR_TRUNC_PREFIX="… /"
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_PREFIX=""

SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=white
SPACESHIP_USER_PREFIX="╭─"
SPACESHIP_USER_SUFFIX=""
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SUFFIX=" "
SPACESHIP_HOST_COLOR_SSH=red

SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  host          # Hostname section
  jobs          # Background jobs indicator
  dir           # Current directory section
  venv          # virtualenv section
  node          # Node.js section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  ruby          # Ruby section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  dotnet        # .NET section
  ember         # Ember.js section
  kubecontext   # Kubectl context section
  line_sep      # Line break
  time          # Time stampts section
  exec_time     # Execution time
  exit_code     # Exit code section
  char          # Prompt character
)
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
plugins=(
  git
  # k
  colorize
  # dirhistory
  copydir
)
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=orange,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green, bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=green'
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'
bindkey '^ ' autosuggest-toggle
export LANG=en_US.UTF-8
#alias cat="colorize"
alias cpd="copydir"
alias l="ls"
alias ll="ls -l"
alias la="ls -la"
alias python=python3
alias drl="python manage.py livereload & python manage.py runserver --livereload-port 9000 &"
alias drs="python manage.py runserver"
alias dsp="python manage.py shell_plus"
alias dmm="python manage.py makemigrations"
alias dmi="python manage.py migrate"
alias dsu="python manage.py createsuperuser"
alias uuu="sudo apt update && yes y | sudo apt upgrade"

xpwd() {
    pwd | xclip -selection clipboard
}
gall() {
    git add .
    git commit -a -m"$1"
    git push
}
manage() {
    python manage.py $1
}
dotup() {
  ./mngDotF.sh
  git add .
  git commit -m "sync"
  git push origin master
}
gsvcred() {
  git config --global credential.helper 'cache --timeout=36000'
}
cpr() {
  rsync -ahr --info=progress2 $1 $2
}
gi() {
  git add .
  git status
  vared -p "Message for commit ([ctrl+c] to cancel): " -c commitMessage
  git commit -m $commitMessage
  git push
  unset commitMessage
}

gim() {
  git add .
  git status
  vared -p "Message for commit ([ctrl+c] to cancel): " -c commitMessage
  git commit -m $commitMessage
  unset commitMessage
}

wwp() {
  tilix -a session-add-right -w ~/code/wwp/wwpfrontend/ -e 'npm run dev'
  tilix -a session-add-right -w ~/code/wwp/
  cd ~/code/wwp/wwpbackend
  workon wwp
  python manage.py runserver localhost:8000
}

sa() {
  eval "$(ssh-agent -s)"
  ssh-add
}

#fpath=($fpath "$HOME/.zfunctions")
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/steven/.config/composer/vendor/bin:/home/steven/.scc/scc.py"
export PATH=~/.npm-global/bin:$PATH
export PATH=$PATH:$HOME/.config/composer/vendor/bin
export PATH=$PATH:/opt/connectiq-sdk/bin
export PATH=$PATH:$HOME/.local/bin

alias scc='/home/steven/.scc/scc.py'
fpath=(~/Documents/cheatsheets/ $fpath)


if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte-2.91.sh
fi